### ISSUE TITLE
It's a question 

### ISSUE THREAD

**Issue by Mercena2007** [skidmaster69420/discord-tokens#10]
Can you tell us how to fix our bot so it doesn't get leaked again?

**Comment by Peter-Maguire** [comment]
use environment variables

**Comment by Mercena2007** [comment]
> use environment variables

Can you dm me for help? I am not sure how to do that. Dãrķ Søŭł#5469

**Comment by Peter-Maguire** [comment]
You should attempt to figure it out yourself through Google first

**Comment by Mercena2007** [comment]
> You should attempt to figure it out yourself through Google first 

Hello, I know how to create an environment variable but please dm me cause I got a question for security purposes.

**Comment by skidmaster69420** [comment]
> Hello, I know how to create an environment variable but please dm me cause I got a question for security purposes.

Security Purposes? Yeah right. I already know what's going on here. You are with the FBI and you are attempting to put squirrel into people's DM's to get them to steal their money. But I'll have you know, that I am from the IRS and I have taken all the squirrels away from you. They work for me now.

Yours
IRS

**Comment by Mercena2007** [comment]
> > Hello, I know how to create an environment variable but please dm me cause I got a question for security purposes.
> 
> Security Purposes? Yeah right. I already know what's going on here. You are with the FBI and you are attempting to put squirrel into people's DM's to get them to steal their money. But I'll have you know, that I am from the IRS and I have taken all the squirrels away from you. They work for me now.
> 
> Yours
> IRS

No, I don't work with the FBI, my developer just wanted to know from where you found the token so he could prevent it the other time. I don't want you to tell me how you found it I just want to know from where. And definitely I am not working for FBI

**Comment by skidmaster69420** [comment]
that sounds like EXACTLY WHAT AN A FBI AGENT would say. I'm on to you, first you put ants in my walls now the fucking squirrels what the fuck. I'm an unpaid intern they don't let me tell you where the tokens come from or else they'll uninstall FORTNIGHT. That CANNOT happen. I think they come in to our top secret token and cocoa warehouse on trailers marked shit like "GITHUBE", "REPPL IT" and "NESTLE® UNDERGROUND". You should check to make sure you're token was not posted onto places like THE FOUR CHAN and VIRUSES. I can't tell you anymore, my boss is coming soon to install the critically acclaimed MMORPG FINAL FANTASY XIV that has a free trial up to level 60 including the Heavensward expansion onto my computer.

BEST,

skidmaster69420 inc llc security group, now sponsored by raid shadow legions (formally nordvpn)

**Comment by Mercena2007** [comment]
> that sounds like EXACTLY WHAT AN A FBI AGENT would say. I'm on to you, first you put ants in my walls now the fucking squirrels what the fuck. I'm an unpaid intern they don't let me tell you where the tokens come from or else they'll uninstall FORTNIGHT. That CANNOT happen. I think they come in to our top secret token and cocoa warehouse on trailers marked shit like "GITHUBE", "REPPL IT" and "NESTLE® UNDERGROUND". You should check to make sure you're token was not posted onto places like THE FOUR CHAN and VIRUSES. I can't tell you anymore, my boss is coming soon to install the critically acclaimed MMORPG FINAL FANTASY XIV that has a free trial up to level 60 including the Heavensward expansion onto my computer.
> 
> BEST,
> 
> skidmaster69420 inc llc security group, now sponsored by raid shadow legions (formally nordvpn)

First I don't work for THE FBI, I don't think that my country even have FBI, second of all I was using replit to test the code and then I will change it to VPS so did you find the token on replit?

**Comment by skidmaster69420** [comment]
Hi there,

Sorry for the confusion. The intern in charge of this issue has had Fortnite and Roblox uninstalled from their computer in response to exposing company secrets.

Unfortunately, we mix all our tokens we find on the internet into a large vat, like strew. As so, we are unable to disclose the location where our highly trained token vultures found your token. Perhaps when you were testing your code, you accidently posted in publicly on your provide like all you millennials do now days with your replit and facebook and "my space".

All the best,

skidmaster69420, LLC. Now sponsored by [Raid: Shadow Legends](https://raidshadowlegends.com/).

**Comment by Mercena2007** [comment]
> Hi there,
> 
> Sorry for the confusion. The intern in charge of this issue has had Fortnite and Roblox uninstalled from their computer in response to exposing company secrets.
> 
> Unfortunately, we mix all our tokens we find on the internet into a large vat, like strew. As so, we are unable to disclose the location where our highly trained token vultures found your token. Perhaps when you were testing your code, you accidently posted it publicly on your profile like all you millennials do now days with your replit and facebook and "my space".
> 
> All the best,
> 
> skidmaster69420, LLC. Now sponsored by [Raid: Shadow Legends](https://raidshadowlegends.com/).

Hi, 

Thank you so much because my developer found the problem, when I was testing the bot I had the token on config.json and replit had the repl public so the token could be seen by everyone. I really wanna thank you because if you hadn't leaked my token so you could make it invalid possible now the bot would have done many bad things, keep the good work up and I wish you the best.

**Comment by skidmaster69420** [comment]
> > Hi there,
> > Sorry for the confusion. The intern in charge of this issue has had Fortnite and Roblox uninstalled from their computer in response to exposing company secrets.
> > Unfortunately, we mix all our tokens we find on the internet into a large vat, like strew. As so, we are unable to disclose the location where our highly trained token vultures found your token. Perhaps when you were testing your code, you accidently posted it publicly on your profile like all you millennials do now days with your replit and facebook and "my space".
> > All the best,
> > skidmaster69420, LLC. Now sponsored by [Raid: Shadow Legends](https://raidshadowlegends.com/).
> 
> Hi,
> 
> Thank you so much because my developer found the problem, when I was testing the bot I had the token on config.json and replit had the repl public so the token could be seen by everyone. I really wanna thank you because if you hadn't leaked my token so you could make it invalid possible now the bot would have done many bad things, keep the good work up and I wish you the best.

Hi Intern here,

we are very glad that you managed to figure out the issue. Unfortunately, I myself have an issue now. I am stuck playing Solitaire my entire shift of 364 days a year, unpaid. I have asked the boss to reinstall Fortnight, but he won't because I exposed "Company Secrets". I have figured out that I am too stupid for Solitaire. I don't even know how it works. And I am stuck with it 364 days a year. So thank you so much, you helped me recognize that I need my Fortnight. So I will try to contact the boss.

Boss you are monitoring the Computer, aren't you? Please respond, I need my Fortnight and Final Fantasy back :c

**Comment by skidmaster69420** [comment]
https://www.wikihow.com/Play-Solitaire
