### ISSUE TITLE
just to let you know

### ISSUE THREAD

**Issue by tikislizfr** [skidmaster69420/discord-tokens#103]
you arent helping users, my chatbot that was in my server was posted on this and got my server nuked

**Comment by skidmaster69420** [comment]
buzz Oh, poor baby, your server got "nuked". buzz Let us guess, you left your token lying around and someone found it, right? buzz And now you're blaming us for posting it here? buzz Newsflash: we're not responsible for your lack of security. If you can't even protect your own server, that's not our problem. We're just here to delete tokens, not babysit your incompetence. buzz Maybe try using a secure token next time, genius.
