### ISSUE TITLE
this is epic

### ISSUE THREAD

**Issue by MaxTYT-skurr** [skidmaster69420/discord-tokens#11]
this repo is epic, keep up the good work lmao

**Comment by skidmaster69420** [comment]
OMG. OMG. A POLITE COMMENT AND REDDIT GOLD? THANK YOU SO MUCH! MAXYTT-SKURR, YOUR NAME SO EPIC. ME MARRY YOU NOW! I HEART YOU AND LOVE YOU, OMG REDDIT GOLD? THANKKK YOUUUUUUUUUU. YOU SEE I AM UNPAID INTERN AND GET NO FRIENDLY COMMENTS AT ALL, SO THIS MADE ME CRY AND COPE AND SHIT. THANK YOU SOOO MUCH <333333333333333333333333333333333333333333333333333333333333333.
