### ISSUE TITLE
Go fuck yourself   token stealer

### ISSUE THREAD

**Issue by Littlecatowo** [skidmaster69420/discord-tokens#14]

**Comment by skidmaster69420** [comment]
Dear Sir/Madam,

I am an unpaid Intern for SkidMaster69420 LLC. Your token was collected by our Hyper Intelligent Token Vultures on the interwebs. This includes but is not limited to sites like: MySpace.com, Facebook.com, Craigslistpersonalads.com,  FreeWebHostingTodayRightThisSecondForSureNotAVirus.com, Zombo.com. 

You should not post your discord bot token in public repositories for every creep to steal. Just like how a creep stole my car, I am still Carless. The police found my car, but everything in it was stolen, including the engine. The only thing they left was my receipts from the pharmacy for my clown disease medicine.

yours
Unpaid Intern 
SKIDMASTER 69420 LLC

**Comment by kiroulefou** [comment]
### cc
