### ISSUE TITLE
Sla

### ISSUE THREAD

**Issue by Teuzindoreplit** [skidmaster69420/discord-tokens#17]
This causes process I think it's better to stop there

**Comment by skidmaster69420** [comment]
Sla? You mean like coleslaw? I fucking love coleslaw and so does the flies. It makes them really happy. Cabbage isn't the best but it's whatever, yanno? I don't really think the flies pose a problem or anything, so I don't really understand why we should stop with the coleslaw? You got famished when you take care of flies all day while learning how to play Solitaire, I'd gladly accept any coleslaw you are offering.

Hopeful future enjoyer of Coleslaw, 

Unpaid Intern
SkidMaster69420, LLC.
