### ISSUE TITLE
you just posted one of my random test bots tokens

### ISSUE THREAD

**Issue by Khaminations** [skidmaster69420/discord-tokens#18]
like what lmaoo how did u even get the random ahh bot token

**Comment by skidmaster69420** [comment]
Dear Khami...

Sorry, even I am not unpaid enough to spell out that name. Anyhow, we get our bot tokens from the balls of camels that were abandoned by their owners. They are then fetched by our Token Vultures. Basically, we have our fly department all over the fucken internet. They are fueled by pure caffeine from GitHub. Then some good old mixture with Meth from the supplier Replit. And finally to finish off the concoction we mix it with lean, from more... obscure places. Sorry, can't leak those the fly police are always listening in on us. Well they are watching me work. Well actually they are watching me exist. They also watch me sleep and shower.... maybe I should put that complaint in with HR.... but they are also flies, so I might not get any support after all. Where were we? Oh yeah, the fly department actually did sponsor the sun landing. I can't tell you much about it, but we did hijack the LITERAL sun. The sun also known as Sol now works for us, but sadly it broke into tears after seeing your grammar, we do expect an handwritten apology letter from you in a language the sun can understand. Now you may ask "What language does the sun speak?" I don't know, that's your Job to find out now.

Yours
Unpaid Intern
Skidmaster69420 LLC
