### ISSUE TITLE
you R

### ISSUE THREAD

**Issue by hiradexo** [skidmaster69420/discord-tokens#2]
you are so dumb you can delete tokens with a simple js code L mother fucker

**Comment by tcrms** [comment]
pretty sure this is for reset them, when you post a token on github it'll email the owner and reset it/force change

**Comment by User9684** [comment]
> you are so dumb you can delete tokens with a simple js code L mother fucker

yes you can lol

**Comment by skidmaster69420** [comment]
Using a token that is not your is against Discord's terms of service. So simply posting it on Github does the invalidation.

**Comment by skidmaster69420** [comment]
Although I decided to give you a sincere response, I have come back after I had 20 Monkeys research an appropriate response.
Sadly, we have to inform you that all 20 Monkeys died trying to process your message. Your English was so terrible, that they all suffered multiple aneurysm. We are holding the funerals, and are asking you to attend. Please bring a gift to support the left-over Monkey Family, this can be any amount of money. 

Thank you sincerely in advance.
