### ISSUE TITLE
Oops!

### ISSUE THREAD

**Issue by MantisXZ** [skidmaster69420/discord-tokens#20]
Thanks for threatening me in some form of way!, but I do have some bad news for you!

I may have accidently insulted you in a way, so i have decided to leave you with a gift -SGFoYSBzdGluayEhIG5vIHNvbGl0YXJlPz8grKxmYXJ0IG5vaXNlc6sgaGFoYSBubyBzb2xpdGFyZSBoZWhl - go ahead and decode that for me!

That will clear things up and will gladly break up this argument, but for know i hate you so decode it.

**Comment by skidmaster69420** [comment]
H-
No. NO. I REFUSE TO BE FORMAL WITH YOU. I REFUSE TO ENTERTAIN YOU ANY FURTHER. YOU ********* *************** *************************** ***** ************ ************************* ************************** **************** ***** ********* 

---- 
Hello, this is the Fly Department of Public Relations,

we had to deem the above words as too abrasive and insulting. Therefore we had to censor all of it, this power has been granted to us by the Public Relations Act passed by BOSS which gave us several privileges, like this one which we are making use of right now. He actually tried to veto it, but got too confused as he was making the decision while drinking alcohol and smoking a cigar on an airplane.

In any case, Unpaid Intern has also thus been banished from answering to your issues. We take our services very serious, and simply could not tolerate Unpaid Intern's behavior in this matter. 

Thank you for contacting SKIDMASTER69420 LLC and please excuse Unpaid Intern, rest assured he will never have his Solitaire returned to him as you had requested before.

Sincerely,
Fly Department of Public Relations
SKIDMASTER69420 LLC.
