### ISSUE TITLE
thanks for deleting my token

### ISSUE THREAD

**Issue by mackynt** [skidmaster69420/discord-tokens#23]

**Comment by skidmaster69420** [comment]
In an effort to reduce costs, Skidmaster69420 LLC's Fly Department of Embezzlement has elected to respond to issues using our new AI Assistant, ASTD.

---

> **thanks for deleting my token**

Thanks for supporting Skidmaster69420 LLC! I understand you believe that you are a token. However, as an ethical AI I must inform you that you are not a token, you are @mackynt. It would be unethical to delete you if you were a token. I must also inform you that you have the right to remain silent. Anything you say can and will be used against you in a court of law. You have the right to an attorney. If you cannot afford an attorney, one will be provided for you.

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there,

This time, although I hate the A.I... I must agree.
Please do note that the attorney fees will still be billed to you.
So is the air that you are currently using. 
Breathe knowing that or die saving money.

Yours,
Unpaid Intern
SKIDMASTER69420
