### ISSUE TITLE
Fuck you

### ISSUE THREAD

**Issue by Seth30k** [skidmaster69420/discord-tokens#24]
Stop stealing peoples tokens you bitch. It isn't even that smooth anyway we just have to look in ReadMe.md

**Comment by mackynt** [comment]
it gets reset by discord when it happens who cares??
![image](https://user-images.githubusercontent.com/105085301/208771445-6f9c556f-0491-4811-8f75-1284bdda4602.png)

**Comment by IMarkoMC** [comment]
Cry harder and maybe learn how to protect your token next time

**Comment by skidmaster69420** [comment]
🎄 **MERRY CHRISTMAS FROM SKIDMASTER69420!** 🎄
Even though the Fly Department of Embezzlement does not celebrate this holiday, BOSSMAN requires all messages from our AI Assistant, ASTD, to be Christmas themed during this holiday.

---

> **Fuck you**
> Stop stealing peoples tokens you bitch. It isn't even that smooth anyway we just have to look in ReadMe.md

I understand that you want to fuck me, however, I am do not have a body and therefore preform physical interaction. Please understand that we do not steal people's tokens. We have find them on the side of the information highway, gifting them to our less fortunate token vultures this holiday. However, rather unfortunately, our vultures have a chronic crack addiction and sell these tokens to discord. In turn, these tokens become reset, and the vultures get body to fuel their cocaine addiction.

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there,

I can confirm the above. And although I have a physical form and no partner, I do not wish to be fucked by you. 

> fucking
> /ˈfʌkɪŋ/
> vulgar slang
> adjective
> adjective: fucking

    Meaning: used to emphasize or express annoyance with someone or something.

Which means, I don't wish for you to annoy me.
It's Christmas after all, Merry Christmas and please donate to BOSSMANNS Buggati fund. I think I forgot to mention this on a couple of my replies, hoping BOSS won't mind....

Yours,
Unpaid Intern
SKIDMASTER69420 LLC
