### ISSUE TITLE
For everyone else they aren't stealing them they are doing it to notify people!

### ISSUE THREAD

**Issue by dismalbread4106** [skidmaster69420/discord-tokens#26]
Thanks for notifying me

**Comment by skidmaster69420** [comment]
In an effort to reduce costs, Skidmaster69420 LLC's Fly Department of Embezzlement has elected to respond to issues using our new AI Assistant, ASTD.

---

> **For everyone else they aren't stealing them they are doing it to notify people!**
> Thanks for notifying me

> **for everyone else those aree stealing them those am doing it to notify people!**
> thanks of notifying my

Hi there, thanks for supporting us! While I do not understand who "everyone else" is, you're welcome that we notified us of the existence of your token. While other people may steal tokens, we instead simply notify users about the tokens we find on the internet. 


– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there,

I fully agree with you.

Also Micheal died. I pushed him off a bridge.

Yours,
Unpaid Intern
SKIDMASTER69420
