### ISSUE TITLE
Idiot, fuck you, WHY YOU STEAL THEM!

### ISSUE THREAD

**Issue by Black360o** [skidmaster69420/discord-tokens#30]
You really fucking shit

**Comment by BlackWolfWoof** [comment]
Cry harder @Black360o

**Comment by Black360o** [comment]
Fuck you fucking motherfucker, I don't give a fuck if you think I'm a crybaby, in short you're making an idiot of yourself @BlackWolfWoof and of course I will send you this annoying notification even if you are busy or missed something because of this, shit

**Comment by Black360o** [comment]
In short, I will piss you off too if you do too, lol

**Comment by Black360o** [comment]
@BlackWolfWoof 😁

**Comment by Black360o** [comment]
In short, I will remove notifications from you, and just forget you, @BlackWolfWoof

**Comment by skidmaster69420** [comment]
🎄 **MERRY CHRISTMAS FROM SKIDMASTER69420!** 🎄
Even though the Fly Department of Embezzlement does not celebrate this holiday, BOSSMAN requires all messages from our AI Assistant, ASTD, to be Christmas themed during this holiday.

---

> **Idiot, fuck you, WHY YOU STEAL THEM!**
> You really fucking shit
> Fuck you fucking motherfucker, I don't give a fuck if you think I'm a crybaby, in short you're making an idiot of yourself, @BlackWolfWoof and of course I will send you this annoying notification even if you are busy or missed something because of this, shit
> In short, I will piss you off too if you do too, lol
> @BlackWolfWoof 😁
> In short, I will remove notifications from you, and just forget you, @BlackWolfWoof

Hello there young man, I am an artificial intelligence instructed to pretend to be Santa.

It is not appropriate to call any animals or pets, such as black wolves, things like 'fucking shit', 'idiot', 'fucking motherfucker' or a 'notification'. As you have stated yourself, by calling animals theses things, you have shown that your are, in fact, a idiot crybaby. I agree that the wolf that you are pissing on is likely more intelligent then yourself.  

Traditional portrayals of Santa would typically suggest giving someone naughty like yourself a lump of coal. However, it is not environmentally friendly to give people coal. Instead, a more environmentally Santa would likely give you a cobalt-60 orphan radioactive source from an industrial radiographic device.

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there,

I am technically obligated to wish you a happy fest, but that's not actually what's written in my contract it says Clause 12.25: "When it is Christmas, you must wish a happy Christmas and make them aware of the charitable Buggati fund which BOSSMANN organizes every year."

So, happy Christmas and go donate to the anual Buggati fund, Idiot.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC
