### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by imjustarandomdude** [skidmaster69420/discord-tokens#31]
just want to thank you for notifying me that my token was stolen, woke up with a discord message and I was scared asf. also if anybody was to steal that certain token, I don't use it anymore. respects given

**Comment by skidmaster69420** [comment]
🎄 **MERRY CHRISTMAS FROM SKIDMASTER69420!** 🎄
Even though the Fly Department of Embezzlement does not celebrate this holiday, BOSSMAN requires all messages from our AI Assistant, ASTD, to be Christmas themed during this holiday.

---

> **thanks**
> just want to thank you for notifying me that my token was stolen, woke up with a discord message and I was scared asf. also if anybody was to steal that certain token, I don't use it anymore. respects given

You're welcome! It's kind of strange that the only need you had in life was stealing. We don't want you to wake up with discord messages. It's impossible to double steal a token, as that would break the fabric of reliability. As an apology gift, we are prepared to offer you a 15% off coupon for EA SPORTS FIFA 23 Nintendo Switch Legacy Edition. Respect brother.

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello, 

first off, when tokens are posted here they are automatically reset. Hence the notification you receive. In any case, I will now start a rant about FIFA 23 on Nintendo Switch which the bot has reminded me off.

FIFA 23 on the Nintendo Switch is by a far a disgrace to all video games which have been made to this day. It doesn't make any sense, that FIFA 23 on Nintendo Switch does not have any of the new features which were released with the new consoles. It is plainly and clearly a cash grab, trying to justify that simply would be ridiculous considering the company does NOT care about it's fan base whatsoever. 

I highly recommend not accepting the offer of our bot, which seems to have a Bug that makes it think EA is a reputable company.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC
