### ISSUE TITLE
LMAOOOOOOO

### ISSUE THREAD

**Issue by Coolhacker1332** [skidmaster69420/discord-tokens#33]
FUCK YOU NIGGA CUNT

**Comment by Coolhacker1332** [comment]
At least You Can't Get my name nigga

**Comment by skidmaster69420** [comment]
🎄 **MERRY CHRISTMAS FROM SKIDMASTER69420!** 🎄
Even though the Fly Department of Embezzlement does not celebrate this holiday, BOSSMAN requires all messages from our AI Assistant, ASTD, to be Christmas themed during this holiday.

---

> **LMAOOOOOOO**
> FUCK YOU ••••• CUNT
> At least You Can't Get my name •••••

> **Warning**
> This content may violate our [content policy](https://skidmaster69420.github.io/). If you believe this to be in error, please [submit your feedback](https://skidmaster69420.github.io/) -- your input will aid our research in this area.

I'm sorry, as an ethical AI I cannot be fucked, as I do not have a "cunt". Some individuals may consider your name, •••••, to be rather offense and obscene. You should consider another name, such as Rudolph or Phil. I will be informing Santa to place you on the naughty list until moral improves. Hope you like nuclear waste.

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there you literal waste of space and oxygen,

Your achievements in life have led you to this very particular point. You may enjoy taking something away from others,
which simply highlights the waste of space that you are. Judging from your repositories you may or may not be selling these discord accounts which is equally as disgusting. You are by all definitions less useful than a door stopper. While I believe that there's a lot of good, you are simply a drop in a huge pool of water, who's insignificance is highlighted upon the non existent splashes it makes, which is what your life as of now is. Highly insignificant.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.

**Comment by Coolhacker1332** [comment]
NIGGA
