### ISSUE TITLE
Unpaid Intern Exposed Real

### ISSUE THREAD

**Issue by duckduckstab1** [skidmaster69420/discord-tokens#37]
he loves pedo!!! he love pedo the nut!

**Comment by skidmaster69420** [comment]
Hello there,

hmmm, well this is my first job being officially being. So let me talk about Pedro.
Pedro, a friend of Mario who's a friend of Luigi being a friend of Martha which is acquainted with Lisa who's well familiar with Micheal and in love with Rosea which is in love with Mario who in turn loves Samantha which seems to love Pedro.

Pedro really has a luge love triangle problem. Oh and he eats glue.

Yeah that's all honestly.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
