### ISSUE TITLE
W

### ISSUE THREAD

**Issue by x8g** [skidmaster69420/discord-tokens#4]
big W but still how do you manage to obtain tokens that are private, the only thing I could think of is people had them on replits & github repos. So do you have a tool(s) that scrapes github / replits for valid bot tokens and see what they're being used for? Then proceed from there since my friend was running a "Nitro Gen" on replit and it managed to get in here. And he got a message from discord support that they reset his token.

**Comment by User9684** [comment]
we're just too good that's how

**Comment by Starlinkboy** [comment]
So @User9684 is claiming to be a part of @skidmaster69420 's team?
Do you know shit bro?

**Comment by User9684** [comment]
@Starlinkboy I know that you're a skid who makes "nitro generators"

**Comment by skidmaster69420** [comment]
@Starlinkboy there is a lot of people who contribute to making skids mad project. Seems like based on your repositories you might be one of those skids that might be mad.

**Comment by Starlinkboy** [comment]
Lmao you skids think that all these repos I make are fake and shit. Go ahead and try then. And I ain't those losers who post their tokens online. So @skidmaster69420 mind your fucking business and @User9684 shut the hell up cuz unlike you I make real shit.

**Comment by IMarkoMC** [comment]
Cry harder

**Comment by User9684** [comment]
Cope and seethe!

**Comment by User9684** [comment]
(Also my bot inside more servers than children you'll ever scam proves I actually make real "shit")

**Comment by Xenorio** [comment]
y'all need a pacifier or something?

**Comment by Starlinkboy** [comment]
Wow @User9684 congrats on 5 servers!!

**Comment by User9684** [comment]
![image](https://user-images.githubusercontent.com/65233836/183804752-3d8013f6-afb1-4da6-bb60-8ec2806c81e8.png)
🤨

**Comment by Starlinkboy** [comment]
Great mate.... having a bot that's not on top.gg not even any Google results.
Is it even ur bot?

**Comment by User9684** [comment]
https://top.gg/bot/875872695697416243 ?

**Comment by Starlinkboy** [comment]
Okay and?

**Comment by User9684** [comment]
mate you said its not on top.gg but it is...
