### ISSUE TITLE
Why are you stealing

### ISSUE THREAD

**Issue by queenhoney-uwu** [skidmaster69420/discord-tokens#40]
### **Why are you stealing my bot token ? ### **Thankfully discord Reset that token if you dare anywhere to steal anybody’s token you’re gonna be so** dead **
- hate you bye

**Comment by skidmaster69420** [comment]
Hello there,

That formation is terrible, not to mention the usage of language. It makes no sense, it isn't even a proper sentence. That aside, you somehow managed to bungle up the sentence so much that I can't actually understand it fully. It probably is modern art, if I were to guess.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.

**Comment by IMarkoMC** [comment]
Stay mad kid
