### ISSUE TITLE
Nice Try ||Sory i forgot to read reason - Thanks

### ISSUE THREAD

**Issue by krica883** [skidmaster69420/discord-tokens#45]
Nice try but discord warn me ;)
No tokens :(
![Screenshot 2023-01-06 203350](https://user-images.githubusercontent.com/73424431/211086206-12dbd917-2aab-4cb6-9c53-ec7e0ad1a3ce.png)

**Comment by skidmaster69420** [comment]
Hello there,

Thank you for thanking us so that we can thank you for thanking us. 
So apparently I actually messed up badly, I wasn't even supposed to mention the XBOX One, I was supposed to mention XBOX Series S. So sorry for that mistake.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
