### ISSUE TITLE
go fuck yourself

### ISSUE THREAD

**Issue by jayson12033021** [skidmaster69420/discord-tokens#47]

**Comment by PRINCE-HERE** [comment]
he saved us

**Comment by IMarkoMC** [comment]
Cry harder

**Comment by skidmaster69420** [comment]
Hello there,

I have finally received my Persona 5 Ann Takamaki figurine, though it is slightly damaged from the Amazon delivery, I have written a 40.000 word complaint to their head of delivery. I have received a lawsuit in response, something of "sending death threats is not permissable by law." what a ridiclous law! Honestly, it's just another debt to add to the pile, though I guess my other debts thus far have all been paid, which is unusal to say the least. 

Oh and to respond to the "go fuck yourself".
You even wrote that sentence incorrectly, you are supposed to write in capital at the beginning of the sentence, so it would be like this "Go fuck yourself.", that is just to show how much of a waste of space you are. Even the air that you are breathing is feeling insulted, honestly go forgive the tree that is making air for you.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
