### ISSUE TITLE
I am mad

### ISSUE THREAD

**Issue by romangraef** [skidmaster69420/discord-tokens#49]
i am mad at the filenames please use `date +"%Y-%m-%d"` so i can sort by date

**Comment by IMarkoMC** [comment]
Cry harder

**Comment by skidmaster69420** [comment]
Dear Sir,

You're mad?! You're MAD?! Look, sorting by date is cool and all, but *why*? Why do you need to sort by date? They're no reason unless you one of those skids that unpaid intern shits on all the time. You know, skids as in shit stains that happen when you poop yourself a little. That describes what people like you are on the underwear that is life. I'll get the bleech.

Yain't,
Alcoholic Fly
