### ISSUE TITLE
scumbag

### ISSUE THREAD

**Issue by notYourSTORM** [skidmaster69420/discord-tokens#56]
why are you posting my bot token here bitch. thankfully discord did a good job
![image](https://user-images.githubusercontent.com/122422291/211713309-ceb57091-1638-4b32-a518-4d83466f9e87.png)

**Comment by wadefield** [comment]
Fr bruh I was just having a normal day and discord messaged me about my token being in used and this mf tryna post my token publicly and I never did anything to this dude but thankfully I resetted the token

**Comment by Chosey98** [comment]
Your tokens were already leaked by someone else so he put them in this repo so discord block them and notify you to reset it

**Comment by notYourSTORM** [comment]
> Your tokens were already leaked by someone else so he put them in this repo so discord block them and notify you to reset it

no they were not . he just assumed it and put it here . why is he even accessing this data .
i didnt asked for it so stop being a hero. it discord which actually saved me this guy just did something that wasnt even needed.

**Comment by IMarkoMC** [comment]
>  i didnt asked for it so stop being a hero. it discord which actually saved me this guy just did something that wasnt even needed.

You left your token in plain text in some random site, the scanners found your token and posted it to GH to avoid others finding your token and doing whatever they want with your token

**Comment by snavward** [comment]
> no they were not . he just assumed it and put it here . why is he even accessing this data . i didnt asked for it so stop being a hero. it discord which actually saved me this guy just did something that wasnt even needed.

Where do you think the scanner found your token? It says in the README exactly what this is and how it works. Next time use proper practices and don't expose your token.

**Comment by skidmaster69420** [comment]
Hello there,

So the Fly Bureau of Investigation slapped me, called me a bitch, put cameras all over my office including the bathroom.
Then they put a bunch of Punjabi No Virus programs on this account. Which honestly, they truly are punjabi no virus.
Punjabi no virus. Punjabi no virus. Punjabi no virus. Punjabi no virus. Punjabi no virus. Punjabi no virus. Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus. 
AH FFS THE AUTOMATIC PUNJABI NO VIRUS KEYBOARD OVERTAKER ACTIVATED AGAIN.
Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.
GOD FUCKEN DAMMMITTTT
Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.
STOPPPPPPPPP
Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.Punjabi no virus. Punjabi no virus.
YOU ARE THE BITCH HONESTLY. YOU ARE THE BITCHHH....
I think it stopped?
Yeah.... I think it did...
bhaad mein jao tum kutiyabhaad mein jao tum kutiyabhaad mein jao tum kutiyabhaad mein jao tum kutiyabhaad mein jao tum kutiyabhaad mein jao tum kutiyabhaad mein jao tum kutiyabhaad mein jao tum kutiyabhaad mein jao tum kutiya
(translated to indian)Fuck you you fucken bitch(translated to indian)Fuck you you fucken bitch(translated to indian)Fuck you you fucken bitch.

Yours,
PUNJABI NO VIRUS
PUNJABI NO VIRUS LLC.
