### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ajusttheguy207** [skidmaster69420/discord-tokens#6]
Fucking that you created! How dare you take my bot token?! And how do you know my bot token???

**Comment by Whanos** [comment]
Calm down.

You published it somewhere online. We posted it here to invalidate it. Store it more securely, in future.

**Comment by skidmaster69420** [comment]
𝓗𝓮𝓵𝓵𝓸 𝓽𝓱𝓮𝓻𝓮,

𝓸𝓾𝓻 𝓱𝔂𝓹𝓮𝓻 𝓲𝓷𝓽𝓮𝓵𝓵𝓲𝓰𝓮𝓷𝓽 𝓽𝓸𝓴𝓮𝓷 𝓼𝓬𝓪𝓷𝓷𝓲𝓷𝓰 𝓭𝓮𝓿𝓲𝓬𝓮 𝓱𝓪𝓼 𝓭𝓮𝓽𝓮𝓬𝓽𝓮𝓭 𝔂𝓸𝓾𝓻 𝓽𝓸𝓴𝓮𝓷 𝓸𝓷 𝓽𝓱𝓮 𝓲𝓷𝓽𝓮𝓻𝓷𝓮𝓽. 𝓢𝓽𝓸𝓹 𝓹𝓸𝓼𝓽𝓲𝓷𝓰 𝔂𝓸𝓾𝓻 𝓽𝓸𝓴𝓮𝓷 𝓸𝓷 𝓽𝓱𝓮 𝓲𝓷𝓽𝓮𝓻𝓷𝓮𝓽, 𝓭𝓾𝓶𝓫𝓪𝓼𝓼.
