### ISSUE TITLE
Help with the security of my bot token's

### ISSUE THREAD

**Issue by Prozoon700** [skidmaster69420/discord-tokens#62]
Hello. I really don't know if I understand what you want to do, but I think your "plan" is good. (I'm not some kind of malicious person, or for evil purposes. It's more I like to help if it's in my power)

On the other hand, I ask for help with the security of my bot's token. Because I have not published the token on any page or public site, so I do not understand how it has been leaked. Could you help me?

(Sorry if something is wrong, I'm Spanish, and I'm using the translator)

**Comment by Prozoon700** [comment]
My bot is host on replit, I don't know if it's matters

**Comment by Peter-Maguire** [comment]
Take a look here: https://docs.replit.com/programming-ide/storing-sensitive-information-environment-variables

**Comment by Prozoon700** [comment]
Like that is how I put the tokens bot, because of I'm confused

**Comment by ConceptualFear** [comment]
For those reading this post, you can report that replit if ya want. But it's easy enough for him to create another replit account and upload the bot to it. I find it entertaining that he uses replit and not his own computer with a VPN. It'd be way easier or something. Idk, stupid is as stupid does.

**Comment by skidmaster69420** [comment]
> For those reading this post, you can report that replit if ya want. But it's easy enough for him to create another replit account and upload the bot to it. I find it entertaining that he uses replit and not his own computer with a VPN. It'd be way easier or something. Idk, stupid is as stupid does.

"stupid is as stupid does."

Thee fucking dareth fig someone with the w'rd "stupid", although thee yourself art the utmost of no more brain than stone.  How dareth thee coequal taketh breath, thee shouldst beest asham'd of running of thy that from which we speak.  F'r the furry council watches ov'r all
