### ISSUE TITLE
Fun fact, you're dumbass LOL. Imagine.

### ISSUE THREAD

**Issue by ConceptualFear** [skidmaster69420/discord-tokens#63]
Imagine stealing discord bot tokens and expecting it to work LMFAO. Every single token in that list is now, get this, _INVALID_! Holy shit! That's some crazy as stuff man, never would've have thought that would happen. 

Big ups though, you have now made every user who owned the token of any bot token listed here very aware of your presence. Oh! And since those are now, big shock, invalid you've also done them a favor by resetting the token. And here's the best part! Those tokens are no longer on the internet! HOLY FUCK?!?! I know right?! That's some mystical sorcery right there. It's amazing how discord is capable of sweeping the internet for exposed tokens. 

Anywho, I know you can just make another GitHub account so there probably isn't any point in reporting you plus all of your repositories...Fuck it, I'm bored ya know. Also, pro tip: Tor Browser. if you don't have the brains for that (which I _think_ was a _little_ clear from the fact that you are using _GitHub_) then I have no clue what you are going to accomplish in the real world. Oh well, not my concerned. Get fucked, your bad, all that yeah yeah. Who cares lmao. 

Have a great night buddy. Hope your year goes well or something.

**Comment by IMarkoMC** [comment]
Lmao that response is so good

**Comment by tcprescott** [comment]
> your bad

you're*

**Comment by tcprescott** [comment]
> And since those are now, big shock, invalid you've also done them a favor by resetting the token.

That's the point

**Comment by GraczBezNicku** [comment]
I can't believe you probably took 5-10 minutes of your life to write this Issue, but didn't bother to read the purpouse of this repository. Absolute idiocy.

**Comment by skidmaster69420** [comment]
Hello there,

You remind of a little child, one that gets offended when they don't get the candy that they promised.
Like a child who's in desperate need of attention, one that believes that they are in the right.
One that can never be wrong, one that is smarter above all else. 
Honestly, insulting you doesn't even do it justice, as any insult would just probably hit a wall.
You are just too right to be wrong, you could never be wrong. You are always right.

Well, my friend.
There's only right thing about this entire thing here though.
One true assumption.
"You are ignorant." that is the right thing here.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
