### ISSUE TITLE
I almost forgot

### ISSUE THREAD

**Issue by ConceptualFear** [skidmaster69420/discord-tokens#64]
Grey hats aren't respected at all. Fun fact. How do I know? Well when you are a grey hat the only respect you'll get is from another grey hat who thinks you are doing something good. Although, that depends on a few things. 

But, I know you don't really care about that. All about doing the good deeds ya? But, who cares. Probably the only thing you are doing is reporting the tokens of people who aren't doing fishy things. And fun fact, I can just about guarantee most of those tokens weren't fishy hahahaha. Such as the one you got in there for my own lil bot. And fun fact, that was a Utility Bot used in the technical department I manage for an organization of about 10k+ members. Good thing that wasn't our main bot! Would've had to do all that really, really crazy work of simply pasting a new token. Shit would've been crazy. Such more work.

**Comment by tcprescott** [comment]
Be more careful with your bot tokens in the future lmao

**Comment by Anu6is** [comment]
> And fun fact, that was a Utility Bot used in the technical department I manage for an organization of about 10k+ members.

So what you're saying is it's actually a good thing that your token got invalidated before someone else found it and used it to mess with your org 👍

**Comment by skidmaster69420** [comment]
Hello there,

You are just the kind of person we want on this Repo, you complete morotic idiot.
"Grey hats"? Don't make me laugh. There's no way exposing Tokens that were already exposed 
makes any difference. This Repo only serves to make sure the bots don't get taken over.

Ridiclous really, you don't even deserve an Update on my situation!

Not yours, 
Unpaid Intern
SKIDMASTER69420 LLC.
