### ISSUE TITLE
how do i fix bot??

### ISSUE THREAD

**Issue by jasonyelah** [skidmaster69420/discord-tokens#65]
i have book bot and now offline becuase you post token. a lot of members lost things in my server because bot is offline and i cannot fix because i dont remember where token is i only code and send code to server manager. he yell at me now because my bot offline. how do i fix?? sorry my english no good. i speak espanol.

**Comment by jasonyelah** [comment]
hello

**Comment by IMarkoMC** [comment]
> i have book bot and now offline becuase you post token. a lot of members lost things in my server because bot is offline and i cannot fix because i dont remember where token is i only code and send code to server manager. he yell at me now because my bot offline. how do i fix?? sorry my english no good. i speak espanol.

Use ENV variables

**Comment by skidmaster69420** [comment]
Hola there, 

I am very impressed that you wrote a Book bot. 
Please consider actually reading an English book to improve that English of yours though.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
