### ISSUE TITLE
Discord took it down lol.

### ISSUE THREAD

**Issue by sp69ky** [skidmaster69420/discord-tokens#66]

**Comment by JohnBarosa78** [comment]
That's the purpose of this repo, to reset the tokens so someone else doesn't get hold of them and nuke your server

**Comment by skidmaster69420** [comment]
Dear sp69ky, 

In an attempt to continue the duties of the entity known as "SKIDMASTER69420 LLC.", we the FBI (Fly Bureau of Investigation.) have taken the liberty of ceasing this account for as long as Unpaid Intern stays under Investigation for entering a court of law with heavy weaponry.

From all we can truly say, while still staying professional is that your token was leaked.

That is all, stay safe citizens.

Sincerely,
The FBI
(Fly Bureau of Investigation)
Flying, Bullshittery, Intellectually.
