### ISSUE TITLE
這出發點確實好...但我只是個學生

### ISSUE THREAD

**Issue by zackzheng1121** [skidmaster69420/discord-tokens#67]
感謝啦...可以重新開啟我的機器人

**Comment by tcprescott** [comment]
Title: That's a good idea...but I'm just a student

Thanks...can restart my bot

**Comment by skidmaster69420** [comment]
Hello there,

I don't speak Chinese. But you are a BAKKAAAA or something like that.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
