### ISSUE TITLE
Bot, false reported

### ISSUE THREAD

**Issue by ASDF123214321** [skidmaster69420/discord-tokens#68]
I am an owner of a private test server, and my server got nuked a year ago. I didn't really care at first, and I am not a scammer/hacker. My bot does not send messages/embeds with QR Codes in them. I believe that my bot has been false reported, and thank you for reading my text.

**Comment by tcprescott** [comment]
Your bot only showed up in this repository because the token was leaked somewhere online.

**Comment by ASDF123214321** [comment]
I have already took action of the event. Thank you for making discord notify me.

**Comment by ASDF123214321** [comment]
Also, where was it found?

**Comment by tcprescott** [comment]
Do you have a public repl.it project?  I think they find most of the tokens in those.  If so, consider using an environmental variable to store the secret.

**Comment by skidmaster69420** [comment]
Hello there,

Well no joke to be made here. Just wath yourself in the future.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
