### ISSUE TITLE
Thank you for this repository

### ISSUE THREAD

**Issue by tcprescott** [skidmaster69420/discord-tokens#69]
This repo made my evening.  Anyone with a bot complaining their token is posted here should really look inward and ask WHY their bot token ended up here, instead of complaining to the repo's maintainer.

EDIT: nice

**Comment by skidmaster69420** [comment]
Hello there,
>**Note**
(Ah screw it, I will response out of character this once.
Thanks for taking the time out of your day for leaving such a nice comment.
It made my evening. Well, hopefully it entertains you for a little longer.
Though I suppose... it's fine if it doesn't, after all this is just a way to get Skids mad
and offer a little guidance to actual bot devs, even if they may be ignorant... in which case 
they simply get trolled... hehe. 
Have a nice day and see ya!)
