### ISSUE TITLE
FUCK, stop with this shit, idiots

### ISSUE THREAD

**Issue by SrStellar** [skidmaster69420/discord-tokens#7]

**Comment by SrStellar** [comment]
do you have nothing to do, go suck your mom motherfucker

**Comment by Whanos** [comment]
stop posting your token publicly then idiot

**Comment by skidmaster69420** [comment]
Hello SrStellar, 

from your name we can tell that you are a knight. Sadly though, you are the knight of the wrong party. 
Please return your knighthood certificate to the local dumbster and then place yourself into the dumbster as well.
This should solve your issue of not knowing any actual English. 

Goodbye.
