### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by nioncodez** [skidmaster69420/discord-tokens#70]
Can you like filter bot tokens & human account tokens thanks!

**Comment by tcprescott** [comment]
I don't see why, it doesn't advance the goal of the repository which is to get Discord to disable leaked tokens.

**Comment by nioncodez** [comment]
Separates tokens , so like if it's user token u can just access that account and like most scammers tokens it finds im assuming so u can just login and nuke their server / expose them

**Comment by skidmaster69420** [comment]
Hello there,

unlike me, well the writer of these comments. The person maintaining this repo actually has a life.
I quiet envy him for that. But well, nothing that could be done about that, I suppose...
So no, no changes.

Right... the signing off.

I wish I had a life.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
