### ISSUE TITLE
DELETE NOW OR YOU WILL GO TO HECK

### ISSUE THREAD

**Issue by CookieRundiscord** [skidmaster69420/discord-tokens#71]
NOW

**Comment by tcprescott** [comment]
LATER

**Comment by IMarkoMC** [comment]
Cry harder

**Comment by CookieRundiscord** [comment]
no you you little baby

**Comment by IMarkoMC** [comment]
> no you you little baby

Who's the one opening a issue to get a random string of text deleted from a repo? lmao

**Comment by skidmaster69420** [comment]
Hello there,

So first things first, you have been very annoying.
Now let us look at the definition of a **baby**.
"adjective
adjective: baby

    comparatively small or immature of its kind."

Immature, that describes you perfectly you baby!

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
