### ISSUE TITLE
I love this project, thank you so much.

### ISSUE THREAD

**Issue by joshcodesthings** [skidmaster69420/discord-tokens#75]
One of my verified bots tokens with thousands of servers got posted on here and I had no fucking idea how this happened, about to go check all my files now, I appreciate you bro.

**Comment by Clpz-is-cool** [comment]
> One of my verified bots tokens with thousands of servers got posted on here and I had no fucking idea how this happened, about to go check all my files now, I appreciate you bro.

it wont do shit anyways, discord instantly changes your token for you right after finding it online

**Comment by skidmaster69420** [comment]
Hello there,

This repo prevents a literal take over of someone elses bots.
That's all it does, that's all it will ever do.

Anyway, thank you for thanking us for helping keep your bot safe.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
