### ISSUE TITLE
[Question] How long does it take for Discord to invalidate tokens which are uploaded to this list?

### ISSUE THREAD

**Issue by Derpitron** [skidmaster69420/discord-tokens#78]
I was looking through this repo after finding it in my Github recommended section.
I commend the effort, but I'm worried that malicious users could be watching these lists, and trying the tokens on them.

Is there some sort of delay between the time that a token is added to the list, and the time that Discord invalidates it? If so, then it creates a window of vulnerability for the tokens to be mass scraped and used by bots.

**Comment by tcprescott** [comment]
The real answer would be Discord providing an endpoint where found tokens can be securely submitted for invalidation.  In the meantime this is still likely the best way to handle it.  The alternative is the tokens get found by people with less than idea intentions.

**Comment by Peter-Maguire** [comment]
It's instant

**Comment by tcprescott** [comment]
Even better

**Comment by Derpitron** [comment]
> It's instant

How do you know?

**Comment by Peter-Maguire** [comment]
Because I've uploaded my own token and watched how long it took

**Comment by skidmaster69420** [comment]
Just checked with our captives: it's instant.

P.S. The Japanese don't like the word "Weeb" but I don't care. It's my culture NOT theirs to like their culture. 私は彼らの文化の奴隷です！
