### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by YazanXda3s** [skidmaster69420/discord-tokens#80]
But like you even published some tokens that are not from scammers, luckly my bots are not in my server anymore and havent used them for a long time, but like now i have to change every bot token i have ?

**Comment by IMarkoMC** [comment]
Discord resets them once they're published.

You should store your tokens in ENV variables because if someone finds your token they can do whatever they want with your bot

**Comment by skidmaster69420** [comment]
Tokens are reset once published. You must generate a new token and stop posting them on the public internet.

P.S. People who dunk OREOs in milk are serial killers. Dunking OREOs in milk isn't even in the bible. When you dunk into milk, you are dunking into the bits of HELL. One day people will write a long-form blog post on paper about these terrible people, and I will be quoted in it. One day Wikipedia will have a page on the "OREO Serial Killer", and this comment will be listed in the citations. These people are monsters that have to be stopped at all costs.
