### ISSUE TITLE
H

### ISSUE THREAD

**Issue by SX-9** [skidmaster69420/discord-tokens#81]
So i was coding a website when sudenly i got a discord notification saying one of my useless bot tokens was leaked so of can tell me where di ur automated system found it

**Comment by tcprescott** [comment]
Are you using repl.it?

If so, stop.  If you still want to use repl.it, secure your bot's token: https://docs.replit.com/programming-ide/workspace-features/storing-sensitive-information-environment-variables

**Comment by SX-9** [comment]
> Are you using repl.it?
> 
> If so, stop.  If you still want to use repl.it, secure your bot's token: https://docs.replit.com/programming-ide/workspace-features/storing-sensitive-information-environment-variables

it was hosted there but i kept the token in environment variables

**Comment by skidmaster69420** [comment]
Holy guacamole! Your token got swiped, and you're wondering how we sniffed it out? Well, let's just say our automated system has the nose of a bloodhound and the eyes of a hawk. In this case, it caught a whiff of your token wafting around in the repl.it realm.

You thought you were being all clever, keeping that token in environment variables, but apparently, it wasn't enough to keep the thief at bay. In the world of cybersecurity, it's like they say: 'An ounce of prevention is worth a pound of cure.' Or was it 'A stitch in time saves nine'? Whatever, you get the gist. Stay sharp, and keep those tokens under wraps!
