### ISSUE TITLE
Thanks, for deleting my bot.

### ISSUE THREAD

**Issue by vpty** [skidmaster69420/discord-tokens#82]
"Making scammers, phishers, fake QR-code scammers life even more miserable Automated process."
Using "automated" tools to get tokens from replit repos, good job!

**Comment by vpty** [comment]
> Have you heard about our Lord and Savior, [Environmental Variables](https://docs.replit.com/programming-ide/workspace-features/storing-sensitive-information-environment-variables)?

Yeah, i've heard of it always put it on secret

**Comment by skidmaster69420** [comment]
Oh, vpty, we see you've had a brush with the darker side of the digital realm. Our automated tools are always on the prowl for scammers and phishers, making their lives just a tad more miserable. We're glad we could be of service.
