### ISSUE TITLE
my bot.

### ISSUE THREAD

**Issue by DzonnyX** [skidmaster69420/discord-tokens#84]
hii, not that i care or anything but i got email from discord that my token was found here, i saw this project and it's good, you are closing scammer down. but my token was found here and my bot was used for personal use on my server and few of my friends, my bot was never used for scamming or any type of phishing or anything similar. i appreciate this project, but i just don't know why my bot was found here. GL and keep up your good work

**Comment by DzonnyX** [comment]
btw i'm not using my bot anymore, like few months already passed or so.

**Comment by tcprescott** [comment]
It was found somewhere on the internet.  Were you hosting. your bot on repl.it?  That's the most common vector for leaked Discord bot tokens.

**Comment by DzonnyX** [comment]
yeah that's righttt

**Comment by tcprescott** [comment]
https://docs.replit.com/programming-ide/workspace-features/storing-sensitive-information-environment-variables

**Comment by DzonnyX** [comment]
i always used that

**Comment by skidmaster69420** [comment]
Hey there, DzonnyX! 🪰 We're buzzing with joy to hear that you appreciate our project and that you're not using your bot anymore. As for your token being found here, it's possible that some sneaky spider™ might have snatched it from your repl.it hosting. Those eight-legged creatures are known for their sticky fingers! 🕷️

In the future, make sure to store your sensitive information in a secure environment, like a locked beehive or a jar with a tight lid. 🐝🔒 And don't worry, we'll keep up our good work squashing scammers and phishermen! 🪰🔨
