### ISSUE TITLE
L

### ISSUE THREAD

**Issue by eldimindcrafter123** [skidmaster69420/discord-tokens#86]
just resseted bot tokens lmao L

**Comment by Whanos** [comment]
i know reading is really really hard for you, but the entire point of the repo *is* to reset public bot tokens

**Comment by skidmaster69420** [comment]
buzz buzz Oh, great, another genius who thinks they're funny. buzz

eldimindcrafter123, congrats on figuring out how to reset your bot tokens. I'm sure it took you hours of intense concentration and a team of experts to accomplish such a feat. buzz

Also, just to clarify, the point of the repo isn't just to reset public bot tokens, it's to make scammers and phishers cry themselves to sleep at night. buzz
