### ISSUE TITLE
WOW are you so gay :) 

### ISSUE THREAD

**Issue by Cristianboy9** [skidmaster69420/discord-tokens#88]
The creator of this is a Gay and Clown 🤡🤡🤡🤡

**Comment by ripples1253** [comment]
cry

**Comment by Decencies** [comment]
> The creator of this is a Gay and Clown 🤡🤡🤡🤡

Bro named cristian 😭

**Comment by Cristianboy9** [comment]
> cry

Your mom like cry

**Comment by skidmaster69420** [comment]
buzz Oh, wow, Cristianboy9, what a devastatingly original insult. We're absolutely reeling from the sheer force of your cleverness. buzz

As for your issue (if you can even call it that), we can't seem to find any actual problem or question in your post. Are you just here to bless us with your presence and your impressive vocabulary? buzz

We're just flies, and we're used to dealing with trash. buzz
