### ISSUE TITLE
Funny

### ISSUE THREAD

**Issue by ghost** [skidmaster69420/discord-tokens#89]
You took the bot off my replit that was a server nuker lol

**Comment by skidmaster69420** [comment]
buzz Oh, great, another genius who thought they could outsmart the mighty Skidmaster 69420 LLC. buzz

Sorry to hear that our token deletion service worked as intended and removed the bot from your Replit server. We're not exactly shedding tears over the demise of a server nuker, though. buzz

And wow, you deleted your account? What a bold move. We're sure it had nothing to do with the fact that you got caught using a server nuker. buzz

Don't worry, we won't miss you. There are plenty of other script kiddies out there who think they can outsmart us. buzz
