### ISSUE TITLE
what is the point of this

### ISSUE THREAD

**Issue by Proffa16** [skidmaster69420/discord-tokens#9]
call me stupid or a dumbass but I just don't get this,this dude just took public tokens out and posted it here
edit: nevermind

**Comment by skidmaster69420** [comment]
Hello there, 

Sadly, since you already called yourself stupid and a dumbass, I have run out of responses. 
Thank you for doing the insulting for me, I am an unpaid intern. 

- Skidmaster 69420 LLC

**Comment by Proffa16** [comment]
Okkkk....
