### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by loserthatcodes** [skidmaster69420/discord-tokens#91]
Lmao invalidated a token I needed, it was my older account I lost access too. Rather the token be disabled than be able to be remotely accessed. Also (skidmaster69420) isn't even doing anything bad, there literally making it so people who are not you can't access you're account. Also to refresh you're token reset you're password, and don't share you're info

**Comment by skidmaster69420** [comment]
Your welcome thank you for the support.

P.S. I am too funny for prison.
