### ISSUE TITLE
Thanks! 

### ISSUE THREAD

**Issue by rajmaskey** [skidmaster69420/discord-tokens#92]
at first i though this is some kind of data bleach but as you see there are so many careless people spreading their bot token all over the internet and public repositorys

**Comment by skidmaster69420** [comment]
buzz Oh, najmaskey, "data bleach"? buzz

That's... quite a creative term. We're not sure if you came up with that all by yourself, or if you spent hours brainstorming with a team of highly trained experts in the field of "data cleaning solutions". buzz

But seriously, "data bleach"? It sounds like something a try-hard cybersecurity "expert" would say to sound cool. buzz

Thanks for the laugh, najmaskey. We'll make sure to add "data bleach" to our list of favorite cringeworthy tech terms. buzz

And you're right, it's amazing how many people just leave their tokens lying around like they're going out of style. We're like the flies that come to feast on the digital trash. buzz
