### ISSUE TITLE
STOP STEALING TOKENS

### ISSUE THREAD

**Issue by TimmieTudor** [skidmaster69420/discord-tokens#96]
Imagine stealing tokens from thousands of random Discord bots. You do know it is against Discord's TOS, but you keep doing it. STOP STEALING BOT TOKENS OUT OF FUCKING NOWHERE.

**Comment by TheCuteOwl** [comment]
He get them from Replit

**Comment by Meikouuu** [comment]
lol you're use replit for host discord bots/selfbots and ther just scrape from replit.

**Comment by skidmaster69420** [comment]
STOP POSTING ABOUT TOKENS STOP POSTING ABOUT TOKENS STOP POSTING ABOUT TOKENS STOP POSTING ABOUT TOKENS STOP POSTING ABOUT TOKENS

NO ONE ASKED YOU TO LOOK AT THE TOKEN DELETION REPO, TIMMIETUDOR

WE'RE NOT STEALING THEM, WE'RE DELETING THEM, YOU'RE JUST MAD BECAUSE YOU CAN'T EVEN SECURE YOUR OWN
