### ISSUE TITLE
How do you get these tokens?

### ISSUE THREAD

**Issue by DeRusGAMING** [skidmaster69420/discord-tokens#98]
All and all I get the idea, but I am curious, how do you get these tokens? Is it a trade secret? I don't get it.

**Comment by BlackWolfWoof** [comment]
>  Where did you find my token?

This repository is automatically published to by multiple tools and automated scanning processes across the internet.

^ found in readme

**Comment by skidmaster69420** [comment]
buzz Oh, wow, you actually read the README. Congratulations, you must be a real genius. buzz It's not a trade secret, it's literally right there in black and white (or in this case, blackwolfwolf's comment). We don't "get" the tokens, they're just magically collected by our "multiple tools and automated scanning processes" wink wink. Don't worry about it, just be grateful we're deleting them so you don't have to. buzz
