### ISSUE TITLE
My Bot

### ISSUE THREAD

**Issue by Caiden-P** [skidmaster69420/discord-tokens#99]
My bot is wrongfully on this list? Ren's ChatBot AI i was just working on a little chatbot that i eventually stopped working on i dont care about it really but im just confused?

**Comment by skidmaster69420** [comment]
buzz Oh, poor baby, your bot's token got exposed and now it's on our list. buzz Newsflash: if you leave your token lying around on repl.it, it's not our problem. 


Just take it as a free lesson in bot security and move on. Next!
